//
//  ModelSchema.swift
//  LLVS
//
//  Created by Drew McCormack on 21/09/2026.
//

import Foundation

/// How a model property is stored in its SQLite column, and what has to happen at the
/// boundary to turn one into the other.
///
/// Every case names the *semantic* type rather than just the SQLite one, because the SQLite
/// type is not enough to convert by. `Int`, `Bool` and `Date` are all `INTEGER`, and each
/// needs different handling: a `Bool` must reach `Codable` as `true`, not `1`, and a `Date`
/// column holds Unix seconds while `Codable` wants seconds since 2001. Keying the conversion
/// on the declaration string got both of those wrong, silently, because a wrong conversion
/// still produces a number.
///
/// Switching on this enum instead means a type that needs new handling is a compile error
/// rather than a wrong answer.
public enum ColumnStorage: Sendable, Equatable {
    /// `TEXT`, holding the string itself.
    case text

    /// `INTEGER`, holding a whole number.
    case integer

    /// `REAL`, holding a floating-point number.
    case real

    /// `BLOB`, holding the bytes. `Codable` carries these as base64, so the boundary converts.
    case blob

    /// `INTEGER`, holding 0 or 1. Distinct from `integer` because `Codable` requires a JSON
    /// `true`/`false` and rejects a number.
    case boolean

    /// `INTEGER`, holding Unix seconds. Distinct from `integer` because `Codable` encodes a
    /// `Date` as seconds since 2001, while `strftime('%s')` and every other SQLite tool mean
    /// seconds since 1970. The column holds Unix seconds so ordinary SQL means what it says.
    case date

    /// `TEXT`, holding the UUID string.
    case uuid

    /// `TEXT` holding JSON, for a property whose type has no column shape — an array, a
    /// dictionary, a nested struct. Still queryable through `json_extract` and `json_each`,
    /// and an expression index can be built over it.
    case json

    /// The SQLite column type this is stored in.
    public var declaration: String {
        switch self {
        case .text, .uuid, .json: return "TEXT"
        case .integer, .boolean, .date: return "INTEGER"
        case .real: return "REAL"
        case .blob: return "BLOB"
        }
    }
}

/// One column of the table a model maps to.
public struct ModelColumn: Sendable, Equatable {

    /// The property in the Swift type. This is what the stored JSON is keyed by, so it is
    /// what the model decodes from; the column name stops at the table.
    public let propertyName: String

    /// The column in SQLite: `propertyName` snake-cased, with a trailing underscore if it
    /// would otherwise collide with a SQLite keyword.
    public let columnName: String

    public let storage: ColumnStorage

    /// The SQLite type, for example `"TEXT"` or `"INTEGER"`. Derived from `storage`, so the
    /// two cannot disagree.
    public var declaration: String { storage.declaration }

    public init(propertyName: String, columnName: String, storage: ColumnStorage) {
        self.propertyName = propertyName
        self.columnName = columnName
        self.storage = storage
    }
}

/// The table a model maps to, generated by `@MergeableModel`.
public struct ModelSchema: Sendable, Equatable {

    public let columns: [ModelColumn]

    /// Properties the macro could not give a column, because their type is inferred rather
    /// than written down. A macro sees only syntax, so `var count = 0` has no visible type.
    /// Annotate it — `var count: Int = 0` — to get a column.
    public let propertiesWithoutColumns: [String]

    /// Properties stored as JSON, with the type name as written, keyed by property.
    ///
    /// For an array, a dictionary or a nested struct this is expected and correct. It is
    /// worth checking for one surprise: a macro cannot resolve a `typealias`, because that
    /// needs type checking and a macro sees only syntax. So `typealias Title = String` with
    /// `var title: Title` lands here rather than in a `TEXT` column that could be indexed.
    /// Write the underlying type if you want the column.
    public let propertiesStoredAsJSON: [String: String]

    public init(
        columns: [ModelColumn],
        propertiesWithoutColumns: [String] = [],
        propertiesStoredAsJSON: [String: String] = [:]
    ) {
        self.columns = columns
        self.propertiesWithoutColumns = propertiesWithoutColumns
        self.propertiesStoredAsJSON = propertiesStoredAsJSON
    }
}
