//
//  ModelSchema.swift
//  LLVS
//
//  Created by Drew McCormack on 21/09/2026.
//

import Foundation

/// How a model property is stored in its SQLite column.
public enum ColumnStorage: Sendable, Equatable {
    /// A real column of the value's own type, which an ordinary `CREATE INDEX` can index.
    case scalar

    /// A `TEXT` column holding JSON, for a property whose type has no column shape — an
    /// array, a dictionary, a nested struct. Still queryable through `json_extract` and
    /// `json_each`, and an expression index can be built over it.
    case json
}

/// One column of the table a model maps to.
public struct ModelColumn: Sendable, Equatable {

    /// The property in the Swift type. This is what the stored JSON is keyed by, so it is
    /// what the model decodes from; the column name stops at the table.
    public let propertyName: String

    /// The column in SQLite: `propertyName` snake-cased, with a trailing underscore if it
    /// would otherwise collide with a SQLite keyword.
    public let columnName: String

    /// The SQLite type, for example `"TEXT"` or `"INTEGER"`.
    public let declaration: String

    public let storage: ColumnStorage

    public init(propertyName: String, columnName: String, declaration: String, storage: ColumnStorage) {
        self.propertyName = propertyName
        self.columnName = columnName
        self.declaration = declaration
        self.storage = storage
    }
}

/// The table a model maps to, generated by `@MergeableModel`.
public struct ModelSchema: Sendable, Equatable {

    public let columns: [ModelColumn]

    /// Properties the macro could not give a column, because their type is inferred rather
    /// than written down. A macro sees only syntax, so `var count = 0` has no visible type.
    /// Annotate it — `var count: Int = 0` — to get a column.
    public let propertiesWithoutColumns: [String]

    public init(columns: [ModelColumn], propertiesWithoutColumns: [String] = []) {
        self.columns = columns
        self.propertiesWithoutColumns = propertiesWithoutColumns
    }
}
